/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PixelService } from "../pixel.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PixelCreateInput } from "./PixelCreateInput";
import { Pixel } from "./Pixel";
import { PixelFindManyArgs } from "./PixelFindManyArgs";
import { PixelWhereUniqueInput } from "./PixelWhereUniqueInput";
import { PixelUpdateInput } from "./PixelUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PixelControllerBase {
  constructor(
    protected readonly service: PixelService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Pixel })
  @nestAccessControl.UseRoles({
    resource: "Pixel",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPixel(@common.Body() data: PixelCreateInput): Promise<Pixel> {
    return await this.service.createPixel({
      data: {
        ...data,

        mood: data.mood
          ? {
              connect: data.mood,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        mood: {
          select: {
            id: true,
          },
        },

        note: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        value: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Pixel] })
  @ApiNestedQuery(PixelFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Pixel",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async pixels(@common.Req() request: Request): Promise<Pixel[]> {
    const args = plainToClass(PixelFindManyArgs, request.query);
    return this.service.pixels({
      ...args,
      select: {
        createdAt: true,
        id: true,

        mood: {
          select: {
            id: true,
          },
        },

        note: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        value: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Pixel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Pixel",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async pixel(
    @common.Param() params: PixelWhereUniqueInput
  ): Promise<Pixel | null> {
    const result = await this.service.pixel({
      where: params,
      select: {
        createdAt: true,
        id: true,

        mood: {
          select: {
            id: true,
          },
        },

        note: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        value: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Pixel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Pixel",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePixel(
    @common.Param() params: PixelWhereUniqueInput,
    @common.Body() data: PixelUpdateInput
  ): Promise<Pixel | null> {
    try {
      return await this.service.updatePixel({
        where: params,
        data: {
          ...data,

          mood: data.mood
            ? {
                connect: data.mood,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          mood: {
            select: {
              id: true,
            },
          },

          note: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          value: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Pixel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Pixel",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePixel(
    @common.Param() params: PixelWhereUniqueInput
  ): Promise<Pixel | null> {
    try {
      return await this.service.deletePixel({
        where: params,
        select: {
          createdAt: true,
          id: true,

          mood: {
            select: {
              id: true,
            },
          },

          note: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          value: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
